version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    volumes:
      - .:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      FLASK_RUN_PORT: 8080
    command: flask run --host=0.0.0.0 --port=8080
    ports:
      - "8080:8080"